name: Deploy
on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true

      - name: Build
        run: go build -o build/vajeh-cli

      - name: Bump version
        id: version
        run: echo "::set-output name=version::$(./build/vajeh-cli version --minor)"

      - run: echo ${{ steps.version.outputs.version }}

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: build/vajeh-cli
          tag_name: ${{ steps.version.outputs.version }}

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: artronics
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: artronics/vajeh-cli:latest
