name: Deploy
on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true

      - name: Build
        run: go build -o build/vajeh-cli

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: artronics
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: artronics/vajeh-cli:latest
