name: Release
on:
  push:
    branches:
      - master

jobs:
  release:
    name: Deploy
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
          cache: true

      - name: Build
        run: go build -o build/vajeh-cli

      - name: Check
        run: |
          echo message ${{ github.event.head_commit.message }}
          echo  ${{ github.event.head_commit.message == '[release:+major]' }}

      - name: Bump version
        id: version
        run: |
          ./build/vajeh-cli config init -y
          echo "version=$(./build/vajeh-cli version --with-prefix --parse-message ${{ github.event.head_commit.message }})" >> $GITHUB_OUTPUT

      - name: Push version changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: ${{ steps.version.outputs.version }}
          tagging_message: ${{ steps.version.outputs.version }}
          file_pattern: 'release.yaml'

      - name: Release if version selected
        uses: softprops/action-gh-release@v1
        if: ${{ steps.version.outputs.version != '' }}
        with:
          files: build/vajeh-cli
          tag_name: ${{ steps.version.outputs.version }}

  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [release]
    steps:
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: artronics
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push :master
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: artronics/vajeh-cli:master

      - name: Build and push :latest
        uses: docker/build-push-action@v3
        if: ${{ needs.release.outputs.version != '' }}
        with:
          push: true
          tags: artronics/vajeh-cli:latest,artronics/vajeh-cli:${{ needs.release.outputs.version }}
